### ISSUE TITLE
Improvement: Pass the ProgressMonitor for the refresh-action (referencing issue #17)

### ISSUE THREAD

**Issue by oilid** [ContextQuickie/ContextQuickie#18]
Hey,

sorry for disturbing again :-)
Just one question/improvement. Is it possible to pass the eclipse ProgressMonitor for the refresh-action after the process (referencing issue #17)?

For example by using the IRunnableWithProgress like this:
```
PlatformUI.getWorkbench().getProgressService().
            run(true, true, new IRunnableWithProgress() {

                @Override
                public void run(IProgressMonitor monitor) throws InvocationTargetException,
                        InterruptedException {
                        [...]
                        this.process.waitFor(); // for replacing your: while (this.process.isAlive())
                        // Should we test the exitCode of waitFor() for "0" to refresh only in this case?
                        // Or is it possible by the process (TortoiseSVN) to change resources
                        // even if the process was unsuccessful e.g. an aborted merge...?
                        resource.refreshLocal(IResource.DEPTH_INFINITE, monitor);
                        [...]
                }
});
```
This code could is untested and only written by checking the eclipse API ;-)
I think, it would be really great for the user to see the refresh-action as usual in eclipse.

Can you give this improvement a chance? Of course, i will test it again :-)

**Comment by ContextQuickie** [comment]
Hi,
I did a short test but every time I execute any Tortoise command the window shown in the attached image is active and blocks the whole Eclipse UI. Do you know if I can "minimize" it to the progress view?
![progressinformation](https://user-images.githubusercontent.com/15061118/42651959-39b390d8-8611-11e8-986c-381e4899b144.PNG)

**Comment by oilid** [comment]
Unfortunately not out of the box because I never wrote an eclipse plugin :(
But this could may helps you: https://www.eclipse.org/forums/index.php/t/132026/#msg_num_2

But I can ask a colleague tomorrow who has some experience (I hope ;))

**Comment by ContextQuickie** [comment]
Can you please have a look at the attached build?
[ContextQuickie_0.8.4.201807122101.zip](https://github.com/ContextQuickie/ContextQuickie/files/2189925/ContextQuickie_0.8.4.201807122101.zip)

**Comment by oilid** [comment]
Hey,

now I'm getting the following exception:

```
java.lang.Error: Unresolved compilation problem: 
	Multi-catch parameters are not allowed for source level below 1.7

	at contextquickie.tools.ResourceRefresher.run(ResourceRefresher.java:41)
	at contextquickie.tools.ProcessWrapper.executeCommand(ProcessWrapper.java:79)
	at contextquickie.handlers.tortoise.AbstractTortoiseCommand.execute(AbstractTortoiseCommand.java:101)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:431)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:446)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
```
Although I'm using JDK 1.8 in eclipse as default:

```
eclipse.buildId=unknown
java.version=1.8.0_72
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data C:/test/work
```
Is your plugin in that version 0.8.4 using JDK 1.6?

**Comment by ContextQuickie** [comment]
The problem occurs because the plugin specifies  Java 1.6 as the minimum execution environment required. I attached an update which should fix the problem.

[ContextQuickie_0.8.4.201807151008.zip](https://github.com/ContextQuickie/ContextQuickie/files/2195560/ContextQuickie_0.8.4.201807151008.zip)

**Comment by oilid** [comment]
Yeah, that's it now! Great, thanks a lot.

Could you release it again?

**Comment by oilid** [comment]
Okay, an option is useful. I'm now testing your release 0.8.4. I only noticed that the progress bar with "ContextQuickie progress" and "refreshing workspace" is always showing "(0%)" and then suddently is finished. So there is no real progress for the refresh (as opposite to the normal resource refresh - hitting F5...). But it's not so important.
Maybe if you like some time can you have a look if this progress bar option is realizable?

**Comment by ContextQuickie** [comment]
I had a look at the eclipse API and there are probably two ways for reporting progress:
- Calculate the progress based on the number of selected elements in the project. I don't know if this is very useful because I assume in the most cases only a few items will be selected (Tell me if you are doing it in a different way). There won't be a big changed regarding to the current implementation.
- Pass the existing ContextQuickie monitor object to the refresh process of every selected element. This will report the refresh process for all selected elements. The (possible) disadvantage is that the progress will start from zero for every selected element. I attached an example implemention, you can check the behavior if you want.
[ContextQuickie_0.8.5.201807172012.zip](https://github.com/ContextQuickie/ContextQuickie/files/2202852/ContextQuickie_0.8.5.201807172012.zip)

**Comment by oilid** [comment]
Yes, I think the same. Specially me I only select one item usually.
But your new updated version is great. It's exactly that what I excepted. I tested it now and it works :-)
Thanks again!

**Comment by oilid** [comment]
But I still have a question. Wouldn't it be better to remove the "progress bar" with the message "Running external application"? In my opinion it has nothing to do with a progress and the user thinks hitting the red stop button will cancel the external application which isn't the case...

**Comment by ContextQuickie** [comment]
I added a configuration option to disable showing the progress of the execution of external tools. If it is enabled, it is also possible to terminate the execution of the external tool. This changes will be included in the next release

**Comment by oilid** [comment]
Hey,

thanks! What do you think, when the next release (0.8.5?) will be available?

Best regards :-)

**Comment by ContextQuickie** [comment]
I'm currently working on issue #19, as soon as it is fixed there will be a new release.

**Comment by oilid** [comment]
okay great :-)

**Comment by oilid** [comment]
hey,

this option is not working:
![grafik](https://user-images.githubusercontent.com/8297705/43249901-417122f8-90bc-11e8-953f-a7f86829f718.png)

Even if it is deactivated the progress bar for "running the external application" is shown. So the option (activated/deactivated) has no affect...

Can you fix it? By the way: I'm not available the next days, so I can't test it...

**Comment by ContextQuickie** [comment]
Yes and no. The option is intended to be used if the option "Refresh workspace after executing external tools" is not enabled. If the workspace refresh is enabled, the plugin has to wait until the execution of the external tool has been finished. Then it shows the wait process and refreshes the workspace afterwards.
If you disable the workspace refresh, the option for showing the progress will only display the execution status and doesn't refresh anything afterwards. Maybe it's a little bit confusing, currently I didn't have any idea how for an good (readable) implementation to not show the progress but refresh the workspace after execution.

**Comment by oilid** [comment]
Hey @ContextQuickie,

I'm back from holiday :-)

Can't you easy remove (or surround with an configurable option) this code in the _ProcessWrapper_?

``monitor.setTaskName("Running external application");

if (monitor.isCanceled())
        {
          ProcessWrapper.this.process.destroy();
          return Status.CANCEL_STATUS;
}``

Best regards,
Oilid

**Comment by ContextQuickie** [comment]
Yes, but i'm not sure if this results in the expected behavior. If I do that, you'll see a progress bar "ContextQuicke Progress" without the additional text "Running external application" while executing external tools.

**Comment by ContextQuickie** [comment]
Can you please have a look at version 0.9.0? Is this the behavior you're expecting?

**Comment by oilid** [comment]
Yes, Thats it. It works as expected. Thanks a lot!
